name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift-build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build
